spring:
  application:
    name: kglsys-app
  datasource:
    url: jdbc:mysql://localhost:3306/devdb2?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  web:
    resources:
      add-mappings: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
      enable_lazy_load_no_trans: true

server:
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: never
    include-exception: false
  port: 8888

logging:
  level:
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: error


# JWT Configuration
# IMPORTANT: Use a long, random, base64-encoded string for production.
# You can generate one here: https://www.allkeysgenerator.com/Random/Security-Encryption-Key-Generator.aspx
kglsys.jwt.secret: your-super-secret-key-that-is-long-and-secure-and-should-be-in-env-vars
kglsys.jwt.expiration-ms: 86400000 # 24 hours